CREATE TABLE IF NOT EXISTS Card (
    id          TEXT        NOT NULL        PRIMARY KEY,
    type        TEXT        NOT NULL,
    title       TEXT        NOT NULL,
    answer      TEXT        NOT NULL,
    number      INTEGER     NOT NULL,
    tip         TEXT,
    image_path  TEXT,
    sound_path  TEXT
);

CREATE TABLE IF NOT EXISTS Line (
    id          INTEGER     NOT NULL        PRIMARY KEY     AUTOINCREMENT,
    card_id     TEXT        NOT NULL,
    line        TEXT        NOT NULL,
    FOREIGN KEY (card_id) REFERENCES Card(id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

INSERT INTO Card(id, type, title, answer, tip, number) VALUES
('e3dcm1q_1', 'question', 'Espaces 3D', 30, 'aide', 1),
('e3dcm1q_2', 'question', 'Espaces 3D', 30, 'aide', 2),
('e3dcm1q_3', 'question', 'Espaces 3D', 30, 'aide', 3),
('e3dcm1q_4', 'question', 'Espaces 3D', 30, 'aide', 4),
('e3dcm1q_5', 'question', 'Espaces 3D', 30, 'aide', 5),
('e3dcm1q_6', 'question', 'Espaces 3D', 30, 'aide', 6),
('e3dcm1q_7', 'question', 'Espaces 3D', 30, 'aide', 7),
('e3dcm1q_8', 'question', 'Espaces 3D', 30, 'aide', 8),
('e3dcm1q_9', 'question', 'Espaces 3D', 30, 'aide', 9),
('e3dcm1q_10', 'question', 'Espaces 3D', 30, 'aide', 10),
('e3dcm1q_11', 'question', 'Espaces 3D', 30, 'aide', 11),
('e3dcm1q_12', 'question', 'Espaces 3D', 30, 'aide', 12),
('e3dcm1q_13', 'question', 'Espaces 3D', 30, 'aide', 13),
('e3dcm1q_14', 'question', 'Espaces 3D', 30, 'aide', 14),
('e3dcm1q_15', 'question', 'Espaces 3D', 30, 'aide', 15),
('e3dcm1q_16', 'question', 'Espaces 3D', 30, 'aide', 16),
('e3dcm1q_17', 'question', 'Espaces 3D', 30, 'aide', 17),
('e3dcm1q_18', 'question', 'Espaces 3D', 30, 'aide', 18),
('e3dcm1q_19', 'question', 'Espaces 3D', 30, 'aide', 19),
('e3dcm1q_20', 'question', 'Espaces 3D', 30, 'aide', 20),
('e3dcm1q_21', 'question', 'Espaces 3D', 52, 'epitech', 21),
('emcm2q_1', 'question', 'English Maths', 30, 'aide', 1),
('emcm2q_2', 'question', 'English Maths', 30, 'aide', 2),
('emcm2q_3', 'question', 'English Maths', 30, 'aide', 3),
('emcm2q_4', 'question', 'English Maths', 30, 'aide', 4),
('emcm2q_5', 'question', 'English Maths', 30, 'aide', 5),
('emcm2q_6', 'question', 'English Maths', 30, 'aide', 6),
('emcm2q_7', 'question', 'English Maths', 30, 'aide', 7),
('emcm2q_8', 'question', 'English Maths', 30, 'aide', 8),
('emcm2q_9', 'question', 'English Maths', 30, 'aide', 9),
('emcm2q_10', 'question', 'English Maths', 30, 'aide', 10),
('emcm2q_11', 'question', 'English Maths', 30, 'aide', 11),
('emcm2q_12', 'question', 'English Maths', 30, 'aide', 12),
('emcm2q_13', 'question', 'English Maths', 30, 'aide', 13),
('emcm2q_14', 'question', 'English Maths', 30, 'aide', 14),
('emcm2q_15', 'question', 'English Maths', 30, 'aide', 15),
('emcm2q_16', 'question', 'English Maths', 30, 'aide', 16),
('emcm2q_17', 'question', 'English Maths', 30, 'aide', 17),
('emcm2q_18', 'question', 'English Maths', 30, 'aide', 18),
('emcm2q_19', 'question', 'English Maths', 30, 'aide', 19),
('emcm2q_20', 'question', 'English Maths', 30, 'aide', 20);

INSERT INTO Line(card_id, line) VALUES
('e3dcm1q_1', 'Combien y-a-t-il de cubes'),
('e3dcm1q_1', 'dans cette forme ?'),
('e3dcm1q_2', 'Combien y-a-t-il de cubes'),
('e3dcm1q_2', 'dans cette pyramide ?'),
('e3dcm1q_3', 'Combien y-a-t-il de cubes'),
('e3dcm1q_3', 'dans cette pyramide ?'),
('e3dcm1q_4', 'Combien y-a-t-il de petits'),
('e3dcm1q_4', 'cubes dans ce grand cube ?'),
('e3dcm1q_5', 'Combien un cube a-t-il de'),
('e3dcm1q_5', 'faces ?'),
('e3dcm1q_6', 'Quel solide peut-on'),
('e3dcm1q_6', 'construire avec un rectangle'),
('e3dcm1q_6', 'et deux cercles ?'),
('e3dcm1q_7', 'Combien d''arêtes a une'),
('e3dcm1q_7', 'pyramide à base carrée ?'),
('e3dcm1q_8', 'Qu''est-ce qu''polyèdre ?'),
('e3dcm1q_9', 'Combien d''arêtes a une'),
('e3dcm1q_9', 'shpère ?'),
('e3dcm1q_10', 'Quel solide peut-on'),
('e3dcm1q_10', 'construire avec un triangle'),
('e3dcm1q_10', 'équilatéral et trois triangles'),
('e3dcm1q_10', 'isocèles ?'),
('e3dcm1q_11', 'Combien un parallélépipède'),
('e3dcm1q_11', 'a-t-il de faces ?'),
('e3dcm1q_12', 'Parmi ces solides lequel est'),
('e3dcm1q_12', 'un polyèdre ?'),
('e3dcm1q_13', 'Combien un parallélépipède'),
('e3dcm1q_13', 'a-t-il de sommets ?'),
('e3dcm1q_14', 'Quel solide peut-on'),
('e3dcm1q_14', 'construire avec six carrés ?'),
('e3dcm1q_15', 'Combien une sphère a-t-elle'),
('e3dcm1q_15', 'de faces ?'),
('e3dcm1q_16', 'Combien d''arêtes a un cône ?'),
('e3dcm1q_17', 'Quel est l''intrus ? Pourquoi ?'),
('e3dcm1q_18', 'Combien un cône a-t-il de'),
('e3dcm1q_18', 'faces ?'),
('e3dcm1q_19', 'Combien ce solide a-t-il de'),
('e3dcm1q_19', 'faces ?'),
('e3dcm1q_20', 'Combien un cylindre a-t-il de'),
('e3dcm1q_20', 'sommets ?'),
('e3dcm1q_21', 'Combien un cylindre a-t-il de'),
('e3dcm1q_21', 'sommets sur cette figure ?'),
('emcm2q_1', 'Compte jusqu''à 20 en anglais.'),
('emcm2q_2', 'Yuna has got four cats, six horses, eight lions and one tiger.'),
('emcm2q_2', 'How many animals has she got ?'),
('emcm2q_3', 'There are six fish in the fish bowl : two are black and the others are white.'),
('emcm2q_3', 'How many white fish are there ?'),
('emcm2q_4', 'A woman has got five sons and two daughters.'),
('emcm2q_4', 'How many kids has she got ?'),
('emcm2q_5', 'In a bus, there are four men, five women and six kids.'),
('emcm2q_5', 'How many people are there in the bus ?'),
('emcm2q_6', 'There are ten balls in a box :'),
('emcm2q_6', 'four yellow balls and red'),
('emcm2q_6', 'balls. How many red balls are'),
('emcm2q_6', 'there ?'),
('emcm2q_7', 'There are four black cats and nine big brown cats in front of the tree.'),
('emcm2q_7', 'How many cats are there ?'),
('emcm2q_8', 'In a lake, there are fourteen fish : two yellow fish, three red fish, four blue fish and grey fish.'),
('emcm2q_8', 'How many grey fish are there ?'),
('emcm2q_9', 'I have got four pens (one blue pen, one red pen, one green pen and one black pen), two rubbers and one ruler.'),
('emcm2q_9', 'How many pens have I got ?'),
('emcm2q_10', 'Achille has got five black dogs and three big red cats.'),
('emcm2q_10', 'How many pets has he got ?'),
('emcm2q_11', 'Mummy is cooking two banana cakes and five apple cakes.'),
('emcm2q_11', 'How many cakes are there ?'),
('emcm2q_12', 'What is thirteen times ten ?'),
('emcm2q_13', 'What is thirty-two minus seven ?'),
('emcm2q_14', 'What is nine times seven ?'),
('emcm2q_15', 'What is one hundred times ten ?'),
('emcm2q_16', 'What is eighty plus forty-five ?'),
('emcm2q_17', 'What is forty-six times four ?'),
('emcm2q_18', 'What is fifty-three'),
('emcm2q_18', 'plus thirty-nine ?'),
('emcm2q_19', 'What is sixty-four times twenty ?'),
('emcm2q_20', 'What is fifty times twenty ?');